# Generated by Django 4.1.5 on 2023-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correntistas',
            fields=[
                ('codigocorrentista', models.AutoField(db_column='CodigoCorrentista', primary_key=True, serialize=False)),
                ('nomecorrentista', models.CharField(db_collation='Latin1_General_CI_AI', db_column='NomeCorrentista', max_length=50)),
                ('email', models.CharField(db_collation='Latin1_General_CI_AI', db_column='Email', max_length=50)),
                ('datacadastro', models.DateTimeField(db_column='DataCadastro')),
                ('saldo', models.DecimalField(db_column='Saldo', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'Correntistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('codigomovimentacao', models.AutoField(db_column='CodigoMovimentacao', primary_key=True, serialize=False)),
                ('tipotransacao', models.CharField(db_collation='Latin1_General_CI_AI', db_column='TipoTransacao', max_length=2)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=4, max_digits=19)),
                ('dataoperacao', models.DateTimeField(db_column='DataOperacao')),
            ],
            options={
                'db_table': 'Movimentacoes',
                'managed': False,
            },
        ),
    ]
